### ISSUE TITLE
Security Vulnerability Issues

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/e-man#31]
There are some security vulnerability issues in the project. Would be awesome to have them fixed.

Steps:
1) Fork the repo
2) Clone your fork into your machine
3) Run `npm audit`
4) Fix the issue
5) Create a PR and make the world a better place :)

**Comment by michaeljones32** [comment]
I have just forked and installed and get 0 vulnerabilities when running an `npm audit` what vulnerabilities are you getting?

**Comment by AhsanAyaz** [comment]
Hey @michaeljones32. 
Thanks for confirming. Github seems to be pointing out these issues. I just tried the audit myself and found no issues. Attached the images related to those warnings.
Thanks for jumping in 👍 

<img width="856" alt="screen shot 2018-10-04 at 5 07 48 pm" src="https://user-images.githubusercontent.com/9844254/46472952-2f0d0780-c7f8-11e8-856c-ddb47ca0009b.png">
<img width="666" alt="screen shot 2018-10-04 at 5 08 07 pm" src="https://user-images.githubusercontent.com/9844254/46472953-2fa59e00-c7f8-11e8-9b50-8a44a9d62c98.png">

**Comment by AhsanAyaz** [comment]
@michaeljones32 I just reviewed the issue.
The problem is in `client/package.json`.
So do `cd client` and then `npm audit` to see the issues.
